apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-cronjob
spec:
  schedule: "*/1 * * * *"  # every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: quakewatch-job
              image: python:3.11-slim
              command: ["python", "-c"]
              args:
                - "print('Running periodic QuakeWatch job...')"
          restartPolicy: OnFailure
