apiVersion: apps/v1
kind: Deployment
metadata:
  name: quakewatch-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: quakewatch
  template:
    metadata:
      labels:
        app: quakewatch
    spec:
      containers:
        - name: quakewatch
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort | default 80 }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: quakewatch-config
            - secretRef:
                name: quakewatch-secret
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path | default "/" }}
              port: {{ .Values.livenessProbe.httpGet.port | default ( .Values.containerPort | default 80 ) }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds | default 10 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path | default "/" }}
              port: {{ .Values.readinessProbe.httpGet.port | default ( .Values.containerPort | default 80 ) }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds | default 3 }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 5 }}
