apiVersion: v1
kind: Service
metadata:
  name: quakewatch-service
  labels:
    app: quakewatch
spec:
  type: NodePort
  selector:
    app: quakewatch
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30010
