apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quakewatch-http-probe
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobLabel: quakewatch-http
  namespaceSelector:
    matchNames: ["quakewatch-test"]
  selector:
    matchLabels:
      app: quakewatch
  endpoints:
    - interval: 30s
      scrapeTimeout: 10s
      # IMPORTANT: use the blackbox /probe endpoint
      path: /probe
      params:
        module: [http_2xx]
        # Pass the target to probe:
        target: ["http://quakewatch-service.quakewatch-test.svc.cluster.local/"]
      # Send the request to the blackbox exporter service
      relabelings:
        - targetLabel: __address__
          replacement: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
