# Default values for quakewatch.

replicaCount: 5

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Leave empty to use Chart.appVersion (likely 1.16.0) or set explicitly, e.g. "1.16.0"
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

# --- Service ---
service:
  # Use NodePort so you can reach it directly (change to ClusterIP if you prefer Ingress/port-forward)
  type: NodePort
  port: 80
  nodePort: 30010  # pick a free NodePort (30000–32767). Avoid 30001 which was used.

# --- Ingress (disabled by default) ---
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
# limits/requests optional

# Container port the app listens on (nginx listens on 80)
containerPort: 80

# Probes aligned to nginx on port 80
livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
